spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
