spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/Microservices_order
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
   
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 9091

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka
